USE [master]
GO

/****** Object:  Database [PDS]    Script Date: 10/19/2017 11:28:07 PM ******/
CREATE DATABASE [PDS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PDS', FILENAME = N'F:\pds-bohol\PDS.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PDS_log', FILENAME = N'F:\pds-bohol\PDS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PDS] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PDS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PDS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PDS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PDS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PDS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PDS] SET ARITHABORT OFF 
GO

ALTER DATABASE [PDS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PDS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PDS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PDS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PDS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PDS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PDS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PDS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PDS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PDS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PDS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PDS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PDS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PDS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PDS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PDS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PDS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PDS] SET RECOVERY FULL 
GO

ALTER DATABASE [PDS] SET  MULTI_USER 
GO

ALTER DATABASE [PDS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PDS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PDS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PDS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PDS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PDS] SET  READ_WRITE 
GO

