//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public Nullable<int> AddressTypeNo { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> MunicipalityNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
