//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int DetailNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public string CommunityTaxNo { get; set; }
        public string IssuedAt { get; set; }
        public Nullable<System.DateTime> IssuedOn { get; set; }
        public Nullable<System.DateTime> DateAccomplished { get; set; }
        public byte[] Signature { get; set; }
        public byte[] Thnumbmark { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
