//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int EducationNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public string EducationLevelNo { get; set; }
        public Nullable<int> SchoolNo { get; set; }
        public Nullable<int> DegreeNo { get; set; }
        public string YearGraduated { get; set; }
        public string HighestLevelEarned { get; set; }
        public Nullable<System.DateTime> InclusiveDate1 { get; set; }
        public Nullable<System.DateTime> InclusiveDate2 { get; set; }
        public string ScholarshipHonor { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual SchoolName SchoolName { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
