//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eligibility
    {
        public int EligibilityNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public string EligibilityName { get; set; }
        public string EligibilityRating { get; set; }
        public Nullable<System.DateTime> EligibilityExamDate { get; set; }
        public string EligibilityExamPlace { get; set; }
        public string EligibilityLicenseNo { get; set; }
        public Nullable<System.DateTime> EligibilityLicenseDate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
