//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experiency
    {
        public int ExperienceNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public Nullable<System.DateTime> ExperienceDate1 { get; set; }
        public Nullable<System.DateTime> ExperienceDate2 { get; set; }
        public string ExperiencePosition { get; set; }
        public string ExperienceOffice { get; set; }
        public Nullable<double> ExperienceSalary { get; set; }
        public string ExperienceSalaryGrade { get; set; }
        public string ExperienceStatus { get; set; }
        public Nullable<bool> ExperienceIsGovernment { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
