//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCredit
    {
        public int LeaveCreditNo { get; set; }
        public Nullable<System.DateTime> CreditFrom { get; set; }
        public Nullable<System.DateTime> CreditTo { get; set; }
        public string Particulars { get; set; }
        public Nullable<double> VacationEarned { get; set; }
        public Nullable<double> VacationDeduction1 { get; set; }
        public Nullable<double> VacationDeduction2 { get; set; }
        public Nullable<double> SickEarned { get; set; }
        public Nullable<double> SickDeduction1 { get; set; }
        public Nullable<double> SickDeduction2 { get; set; }
        public Nullable<int> LeaveApplicationNo { get; set; }
    
        public virtual LeaveApplication LeaveApplication { get; set; }
    }
}
