//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveApplication()
        {
            this.LeaveCredits = new HashSet<LeaveCredit>();
        }
    
        public int LeaveApplicationNo { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<int> LeaveTypeNo { get; set; }
        public Nullable<int> LeaveNo { get; set; }
        public string LeaveSpent { get; set; }
        public string LeaveSpentDetail { get; set; }
        public Nullable<int> LeaveDays { get; set; }
        public Nullable<System.DateTime> LeaveStart { get; set; }
        public Nullable<System.DateTime> LeaveEnd { get; set; }
        public string Commutation { get; set; }
        public string Recommendation { get; set; }
        public string RecommendationDetail { get; set; }
        public Nullable<int> LeaveOfficeNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
    
        public virtual Leaf Leaf { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual Personnel Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveCredit> LeaveCredits { get; set; }
    }
}
