//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveOffice
    {
        public int LeaveOfficeNo { get; set; }
        public Nullable<System.DateTime> DateFiled { get; set; }
        public string Position { get; set; }
        public Nullable<double> BasicSalary { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public string OfficeAgency { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
