//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveAdd
    {
        public int LeaveAddNo { get; set; }
        public Nullable<System.DateTime> LeaveAddDate { get; set; }
        public Nullable<int> LeaveApplicationNo { get; set; }
        public Nullable<int> LeaveCreditNo { get; set; }
    
        public virtual LeaveApplication LeaveApplication { get; set; }
        public virtual LeaveCredit LeaveCredit { get; set; }
    }
}
