//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Municipality()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int MunicipalityNo { get; set; }
        public string MunicipalityName { get; set; }
        public string MunicipalityPostalCode { get; set; }
        public Nullable<int> ProvinceNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Province Province { get; set; }
    }
}
