//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int ParentNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public string ParentFatherSurName { get; set; }
        public string ParentFatherFirstName { get; set; }
        public string ParentFatherMiddeName { get; set; }
        public string ParentMotherSurName { get; set; }
        public string ParentMotherFirstName { get; set; }
        public string ParentMotherMiddleName { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    }
}
