//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDSEntities : DbContext
    {
        public PDSEntities()
            : base("name=PDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<SchoolName> SchoolNames { get; set; }
        public virtual DbSet<Distinction> Distinctions { get; set; }
        public virtual DbSet<Eligibility> Eligibilities { get; set; }
        public virtual DbSet<Experiency> Experiencies { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<Voluntary> Voluntaries { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<Municipality> Municipalities { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Spous> Spouses { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Children> Childrens { get; set; }
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<LeaveOffice> LeaveOffices { get; set; }
        public virtual DbSet<LeaveApplication> LeaveApplications { get; set; }
        public virtual DbSet<Leaf> Leaves { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<LeaveAdd> LeaveAdds { get; set; }
        public virtual DbSet<LeaveCredit> LeaveCredits { get; set; }
    }
}
