//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public Nullable<bool> Q36A_Yes { get; set; }
        public Nullable<bool> Q36B_Yes { get; set; }
        public Nullable<bool> Q36A_No { get; set; }
        public Nullable<bool> Q36B_No { get; set; }
        public string Q36A_YesDetails { get; set; }
        public string Q36B_YesDetails { get; set; }
        public Nullable<bool> Q37A_Yes { get; set; }
        public Nullable<bool> Q37A_No { get; set; }
        public Nullable<bool> Q37B_Yes { get; set; }
        public Nullable<bool> Q37B_No { get; set; }
        public string Q37B_YesDetails { get; set; }
        public Nullable<bool> Q38_Yes { get; set; }
        public Nullable<bool> Q38_No { get; set; }
        public string Q38_YesDetails { get; set; }
        public Nullable<bool> Q39_Yes { get; set; }
        public Nullable<bool> Q39_No { get; set; }
        public string Q39_YesDetails { get; set; }
        public Nullable<bool> Q40_Yes { get; set; }
        public Nullable<bool> Q40_No { get; set; }
        public string Q40_YesDetails { get; set; }
        public Nullable<bool> Q41A_Yes { get; set; }
        public Nullable<bool> Q41A_No { get; set; }
        public string Q41A_YesDetails { get; set; }
        public Nullable<bool> Q41B_Yes { get; set; }
        public Nullable<bool> Q41B_No { get; set; }
        public string Q41B_YesDetails { get; set; }
        public Nullable<bool> Q41C_Yes { get; set; }
        public Nullable<bool> Q41C_No { get; set; }
        public string Q41C_YesDetails { get; set; }
        public string Q37A_YesDetails { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
