//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int ReferenceNo { get; set; }
        public int PersonnelNo { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceAddress { get; set; }
        public string ReferenceTelNo { get; set; }
        public Nullable<bool> ReferenceIsAcive { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
