//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public string TrainingName { get; set; }
        public Nullable<System.DateTime> TrainingDate1 { get; set; }
        public Nullable<System.DateTime> TrainingDate2 { get; set; }
        public Nullable<double> TrainingNoHours { get; set; }
        public string TrainingSponsor { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
