//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDSSystem.dal.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voluntary
    {
        public int VoluntaryNo { get; set; }
        public Nullable<int> PersonnelNo { get; set; }
        public string VoluntaryOrganization { get; set; }
        public Nullable<System.DateTime> VoluntaryDate1 { get; set; }
        public Nullable<System.DateTime> VoluntaryDate2 { get; set; }
        public Nullable<double> VoluntaryNoHours { get; set; }
        public string VoluntaryPosition { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
